version: "3.7"

services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    networks:
      - n8n_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  postgres_data:
    external: true
    name: postgres_data

networks:
  n8n_network:
    external: true
    name: ${DOCKER_NETWORK}
