version: "3.7"

services:
  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --port
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - n8n_network
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  redis_data:
    external: true
    name: redis_data

networks:
  n8n_network:
    external: true
    name: ${DOCKER_NETWORK}
